In [4]:
import numpy as np

In [6]:
array_one = np.array([0, 1, 3, 5, 9])
array_one

array([0, 1, 3, 5, 9])

In [8]:
num = [11, 22, 33, 44, 55, 66, 77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [10]:
array_of_zeros = np.zeros((2, 3))
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
array_of_ones = np.ones((3, 2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
array_of_ones = np.ones((3, 2), dtype=np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [16]:
array_empty = np.empty((3, 2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
array_of_evens = np.arange(2, 24, 2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [22]:
array_of_floats = np.arange(1, 3, 0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [24]:
array_2D = np.array([(3, 4, 6), (2, 1, 6)])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

In [26]:
array_2D.shape

(2, 3)

In [28]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
array_ND = np.arange(8).reshape(2, 4)
array_ND

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
array_ND = np.arange(6).reshape(2, 4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [36]:
array_ND

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
array_ones = np.ones_like(array_ND)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])