In [1]:
# Broadcasting - Allows operations on arrays with mismatched shapes.
# The smaller array is 'broadcasted' until it matches the size of the larger array.
# Broadcasting will not work with every single array, there are certain restrictions on the shapes of the arrays.
# The two arrays being operated on does not have to be of the same shape.

In [3]:
# Broadcasting Scalars - Operations between scalars and arrays are always possible; the scalar is broadcasted over the array.
# Broadcasting Arrays - Operations between two arrays are possible only under certain conditions; smaller array broadcasted over the larger array.

In [5]:
import numpy as np

In [7]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([5, 5, 5, 5, 5])

In [9]:
x * y

array([10, 20, 30, 40, 50])

In [11]:
z = 10

In [15]:
# Scalar Z broadcasted over Array X.
x * z

array([ 20,  40,  60,  80, 100])

In [17]:
ones = np.ones((3, 4))

In [19]:
ones * z

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [21]:
top_speeds = [184, 243, 192, 309, 257, 218]
weights = [1178, 1243, 1403, 1047, 1673, 1475]

In [23]:
car_info = np.array([top_speeds, weights])
car_info

array([[ 184,  243,  192,  309,  257,  218],
       [1178, 1243, 1403, 1047, 1673, 1475]])

In [29]:
# 1 km = 0.621371 miles.
# 1 kg = 2.20462 lbs.
conversion_factors = np.array([0.621371, 2.20462])
conversion_factors

array([0.621371, 2.20462 ])

In [31]:
conversion_factors.shape

(2,)

In [33]:
car_info.shape

(2, 6)

In [35]:
car_info * conversion_factors

ValueError: operands could not be broadcast together with shapes (2,6) (2,) 

In [37]:
new_factors = conversion_factors.reshape(2, 1)
new_factors

array([[0.621371],
       [2.20462 ]])

In [39]:
new_factors.shape

(2, 1)

In [41]:
car_info * new_factors

array([[ 114.332264,  150.993153,  119.303232,  192.003639,  159.692347,
         135.458878],
       [2597.04236 , 2740.34266 , 3093.08186 , 2308.23714 , 3688.32926 ,
        3251.8145  ]])