In [1]:
import numpy as np

In [3]:
p = np.array([9, 8, 7])
q = np.array([3, 2, 4])

In [13]:
# Element-By-Element Operation.
# Assumption: Arrays are of the same size.
print(f"p + q = {p + q}")
print(f"p - q = {p - q}")
print(f"p * q = {p * q}")
print(f"p / q = {p / q}")
print(f"p % q = {p % q}")

p + q = [12 10 11]
p - q = [6 6 3]
p * q = [27 16 28]
p / q = [3.   4.   1.75]
p % q = [0 0 3]


In [19]:
print(p % 2)
print(p > 8)

[1 0 1]
[ True False False]


In [17]:
x = np.array([[2, 1], [1, 3]])
y = np.array([[3, 2], [4, 2]])
print(f"x: \n{x}")
print(f"y: \n{y}")

x: 
[[2 1]
 [1 3]]
y: 
[[3 2]
 [4 2]]


In [23]:
x + y

array([[5, 3],
       [5, 5]])

In [25]:
x - y

array([[-1, -1],
       [-3,  1]])

In [27]:
x * y

array([[6, 2],
       [4, 6]])

In [33]:
# Dot Product.
x.dot(y)

array([[10,  6],
       [15,  8]])

In [35]:
# Dot Product.
np.dot(x, y)

array([[10,  6],
       [15,  8]])

In [39]:
print(x)
x *= 4
x

[[ 8  4]
 [ 4 12]]


array([[32, 16],
       [16, 48]])

In [51]:
# Aggregate Operations on 1D Array.
fleet_mileage = np.array([14130, 37234, 21892, 11479, 6890, 27981])

In [53]:
fleet_mileage.sum()

np.int64(119606)

In [55]:
fleet_mileage.min()

np.int64(6890)

In [57]:
fleet_mileage.max()

np.int64(37234)

In [59]:
print(f"Mean: {fleet_mileage.mean()}")

Mean: 19934.333333333332


In [91]:
# Aggregate Operations on 2D Array.
num = np.arange(16).reshape(4, 4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
num.sum()

np.int64(120)

In [95]:
# Column Aggregate, Axis = 0.
num.sum(axis=0)

array([24, 28, 32, 36])

In [97]:
# Row Aggregate, Axis = 1.
num.sum(axis=1)

array([ 6, 22, 38, 54])

In [99]:
num.min(axis=1)

array([ 0,  4,  8, 12])

In [89]:
num.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5])