In [1]:
import numpy as np

In [5]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
index_bool = x > 6
index_bool

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [9]:
x[index_bool]

array([ 7,  8,  9, 10, 11])

In [11]:
print(x[x > 6])

[ 7  8  9 10 11]


In [13]:
x < 7

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [15]:
np.count_nonzero(x < 7)

7

In [17]:
np.sum(x < 7)

7

In [19]:
np.sum(x < 7, axis=1)

array([4, 3, 0])

In [21]:
np.any(x > 8)

True

In [23]:
np.all(x < 11)

False

In [25]:
np.all(x < 50)

True

In [27]:
np.all(x < 10, axis=1)

array([ True,  True, False])