In [1]:
import numpy as np

In [3]:
x = np.arange(10)**3
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [5]:
x[3]

np.int64(27)

In [7]:
x[-4]

np.int64(216)

In [9]:
x[1:8]

array([  1,   8,  27,  64, 125, 216, 343])

In [11]:
x[3:-3]

array([ 27,  64, 125, 216])

In [13]:
x[:8]

array([  0,   1,   8,  27,  64, 125, 216, 343])

In [15]:
x[3:]

array([ 27,  64, 125, 216, 343, 512, 729])

In [17]:
x[:10:2]

array([  0,   8,  64, 216, 512])

In [19]:
x[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [21]:
companies = np.array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
                      [1938, 1975, 1911, 2006, 2007],
                      [489000, 131000, 380000, 3000, 30000]])
companies

array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
       ['1938', '1975', '1911', '2006', '2007'],
       ['489000', '131000', '380000', '3000', '30000']], dtype='<U21')

In [23]:
companies[0]

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'], dtype='<U21')

In [25]:
companies[:,2]

array(['IBM', '1911', '380000'], dtype='<U21')

In [27]:
companies[0, 2]

np.str_('IBM')

In [29]:
companies[0:2, 2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006']], dtype='<U21')

In [31]:
companies[:, 2:4]

array([['IBM', 'Spotify'],
       ['1911', '2006'],
       ['380000', '3000']], dtype='<U21')

In [33]:
companies[-1,:]

array(['489000', '131000', '380000', '3000', '30000'], dtype='<U21')

In [39]:
companies[0, ...]

array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'], dtype='<U21')

In [41]:
companies[..., 2]

array(['IBM', '1911', '380000'], dtype='<U21')