In [1]:
import numpy as np
import csv

In [3]:
x = np.arange(14)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169])

In [5]:
x[3], x[7], x[9], x[13]

(9, 49, 81, 169)

In [7]:
mask_1 = [3, 7, 9, 13]

In [9]:
x[mask_1]

array([  9,  49,  81, 169])

In [11]:
mask_2 = np.array([[3, 5], [2, 8]])
mask_2

array([[3, 5],
       [2, 8]])

In [13]:
x[mask_2]

array([[ 9, 25],
       [ 4, 64]])

In [17]:
row = np.array([[0, 0], [2, 2]])
col = np.array([[0, 2], [0, 0]])

In [15]:
cities = np.array([['Sydney', 'Auckland', 'Vancouver'],
                   ['Lima', 'Bogota', 'Lisbon'],
                   ['Istanbul', 'Tehran', 'Colombo']])

In [19]:
cities[row, col]

array([['Sydney', 'Vancouver'],
       ['Istanbul', 'Istanbul']], dtype='<U9')

In [21]:
cities[1, 2]

'Lisbon'

In [23]:
cities[row, col] = 'aaaa'
cities

array([['aaaa', 'Auckland', 'aaaa'],
       ['Lima', 'Bogota', 'Lisbon'],
       ['aaaa', 'Tehran', 'Colombo']], dtype='<U9')

In [25]:
mask_1

[3, 7, 9, 13]

In [27]:
x[mask_1] = 999
x

array([  0,   1,   4, 999,  16,  25,  36, 999,  64, 999, 100, 121, 144,
       999])